[metadata]
# This includes the license file(s) in the wheel.
# https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file
license_files = LICENSE.txt
[options]
python_requires = >=3.8
packages = find:
include_package_data = true
zip_safe = false
install_requires =
    PyPubSub >= 4.0.3
    wxPython >= 4.1.1
    sys_platform == 'win32'